//User actions
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";

//Todos actions
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const MARK_TODO_COMPLETED_OPTIMISTIC = "MARK_TODO_COMPLETED_OPTIMISTIC";
export const DELETE_TODO_OPTIMISTIC = "DELETE_TODO_OPTIMISTIC";
